{% set name = "intbitset" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73145ff05e4227c76585ff8550638b6a083cd130010b781045d81af58f7b6920

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  imports:
    - intbitset

about:
  home: http://github.com/inveniosoftware/intbitset/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: C-based extension implementing fast integer bit sets.

extra:
  recipe-maintainers:
    - gtonkinhill
